GET http://localhost:8000/api/v1/example

###

GET http://localhost:8000/api/v1/example/5f3cf2ff2a5bc819ad6bd2fb

###

POST http://localhost:8000/api/v1/example HTTP/1.1
content-Type: application/json

{
    "example": "Example with rest-client vscode"
}

###

PUT  http://localhost:8000/api/v1/example/5f3cf2ff2a5bc819ad6bd2fb

###

DELETE http://localhost:8000/api/v1/example/5f3cf2ff2a5bc819ad6bd2fb

###


# Example
POST https://example.com/comments HTTP/1.1
Content-Type: multipart/form-data

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}